parameters:
  image: ubuntu-docker
  key_name: key1
  public_network_id: 514a51ef-0513-49ab-b37b-69d8057383ef
  public_subnet_id: 5a6ef041-515d-40c1-af78-493f72f1f4ec
  name: k8scluster
  pod_network_cidr: 192.167.0.0/16
  os_username: admin
  os_password: VMware1!
  os_domain_id: default
  os_tenant_id: 81fdf51526a9430a949e7f1e032f857c
  keystone_ip: 172.168.0.45
  master_count: 2
  minion_count: 3
  master_flavor: m1.large
  minion_flavor: m1.large
  nameserver: 192.168.0.253
  mgmt_net_cidr: 20.0.0.0/24
  webserver: 192.168.0.252
